// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: yxkmwtchhrohwxcrkjhm

class SupabaseConfig {
  static const String supabaseUrl = 'https://yxkmwtchhrohwxcrkjhm.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4a213dGNoaHJvaHd4Y3JramhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMTM2ODIsImV4cCI6MjA3Nzg4OTY4Mn0.7C6sLmjV1RF-qDBPQaukDlBvRKheIoqQ8_cENveV_KU';
}
